### ISSUE TITLE
3dsmax 2023 support

### ISSUE THREAD

**Issue by AliKavyani** [curtwartenberg/LlamaTools-3dsMax-Plugins#4]
Great Job, The plugin is extremely useful and attractive.
is there any compiled version for 3dsmax 2023?

**Comment by curtwartenberg** [comment]
Hey, the latest release has a build for 2023 and 2024. https://github.com/curtwartenberg/LlamaTools-3dsMax-Plugins/releases/tag/ColorLlama0.4.0
